### ISSUE TITLE
imap::parse::parse_mailbox enters unreachable code

### ISSUE THREAD

**Issue by jonkri** [jonhoo/rust-imap#282]
Hi!

Thanks for a nice library! 😊

I'm getting an “entered unreachable code” error in `parse_mailbox` when calling `select`.

Stack backtrace:

```
thread 'main' panicked at /Users/jonkri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/imap-2.4.1/src/parse.rs:210:21:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/panicking.rs:144:5
   3: imap::parse::parse_mailbox
             at /Users/jonkri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/imap-2.4.1/src/parse.rs:210:21
   4: imap::client::Session<T>::select::{{closure}}
             at /Users/jonkri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/imap-2.4.1/src/client.rs:527:27
   5: core::result::Result<T,E>::and_then
             at /rustc/07dca489ac2d933c78d3c5158e3f43beefeb02ce/library/core/src/result.rs:1316:22
   6: imap::client::Session<T>::select
             at /Users/jonkri/.cargo/registry/src/index.crates.io-6f17d22bba15001f/imap-2.4.1/src/client.rs:523:9
...
```

Debug info:

```
C: a2 SELECT "INBOX"
S: * NO [ALERT] Mailbox is at 98% of STORAGE quota
S: * 488 EXISTS
S: * 0 RECENT
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $Forwarded Forwarded $NotJunk NotJunk $MailFlagBit0 $MailFlagBit1 $MailFlagBit2)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $Forwarded Forwarded $NotJunk NotJunk $MailFlagBit0 $MailFlagBit1 $MailFlagBit2 \*)] Ok
S: * OK [UNSEEN 372] Ok
S: * OK [UIDVALIDITY 1472929726] Ok
S: * OK [UIDNEXT 76827] Ok
S: * OK [HIGHESTMODSEQ 230492] Ok
S: * OK [MAILBOXID (e340ef5b-b551-4b02-8306-ffa6547ad846)] Ok
S: * OK [URLMECH INTERNAL] Ok
S: * OK [ANNOTATIONS 65536] Ok
S: a2 OK [READ-WRITE] Completed
```

Cheers!

**Comment by jonhoo** [comment]
@jonkri Thanks for reporting! Could you give `3.0.0-alpha.12` a try and see if you encounter the same problem there?

**Comment by jonkri** [comment]
@jonhoo: It works like a charm, thank you! 🥳 This issue can be closed from my perspective.
